### PR TITLE
add location module to migration demo feature.

### PR DESCRIPTION
**Pull request by lpwalsh**
@schnippy - @ronaldmulero wanted a very specific location module added to the lizard content type. So I added it and am submitting a request for it.

### CODE REVIEW

**Comment by schnippy** [comment]
@lpwalsh - your branch is in conflict with master because it was not based off the latest changes and the system can't merge the two. Can you update your site to the latest codebase and recreate and recommit your branch to resolve this?

**Comment by lpwalsh** [comment]
@schnippy @dgading helped me fix the conflicts. there should no longer be a conflict. we rebased against master and updated the branch.

**Comment by ronaldmulero** [comment]
@schnippy Please PR that a new Home Address field (using location_cck) is now available for all D7 Lizards and that this PR no longer has conflicts with master and that the UUIDs are no longer overridden.

**Comment by webwags** [comment]
Modify the SCRIPT to include a clear cache and revert all 
On the Drupal 7 site, after installation,

enable the Features module at admin/modules
enable the "migration_demo" feature at admin/structure/features
clear cache then revert the migration_demo feature at admin/structure/features/migration_demo all the items on list and then 'revert components' at the bottom of the page.

**Comment by ronaldmulero** [comment]
@webwags I added "clear all caches" to line 58 of a copy of the latest README.md.

**Pull request merged**
